In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import pickle as pk



In [29]:
dataset.dtypes

Coding Skills            int64
Aptitude Skills          int64
Technical Skills         int64
Communication Skills     int64
Core Knowledge           int64
Presentation Skills      int64
Academic Performance     int64
Puzzle Solving skills    int64
English Proficiency      int64
Programming Skills       int64
Management Skills        int64
Projects                 int64
Internships              int64
Training                 int64
Backlog                  int64
 Placed                  int64
dtype: object

In [30]:
# dataset.loc[dataset[' Placed'] > 49, ' Placed'] = 1 DIDN'T WORK
# dataset.loc[dataset[' Placed'] < 50, ' Placed'] = 0 DIDN'T WORK

# dataset[' Placed'] = np.where(dataset[' Placed'] > 49, 1, dataset[' Placed']) WORKED
# dataset[' Placed'] = np.where(dataset[' Placed'] != 1, 0, dataset[' Placed']) WORKED
dataset.head(20)

Coding Skills   Aptitude Skills  Technical Skills   Communication Skills  \
0               85               85                 90                    30   
1               89               90                 85                    35   
2               80               85                 90                    45   
3               95               90                 90                    20   
4               95               85                 80                    75   
5               90               75                 80                    78   
6               70               79                 80                    78   
7               50               65                 70                    75   
8               60               75                 74                    60   
9               90               91                 85                    71   
10              70               82                 69                    85   
11              94               97                 91                    93   
12              55               89                 65                    80   
13              88               90                 80                    86   
14              45               72                 72                    68   
15              49               70                 65                    55   
16              51               74                 60                    55   
17              65               70                 60                    55   
18              85               70                 65                    60   
19              40               70                 70                    70   

    Core Knowledge  Presentation Skills  Academic Performance  \
0               40                   40                    75   
1               50                   35                    70   
2               55                   45                    78   
3               40                   30                    60   
4               80                   80                    88   
5               85                   84                    76   
6               60                   47                    78   
7               65                   65                    74   
8               70                   75                    80   
9               65                   80                    79   
10              73                   82                    79   
11              90                   94                    90   
12              75                   80                    75   
13              81                   82                    81   
14              45                   55                    55   
15              50                   60                    74   
16              40                   60                    50   
17              50                   40                    65   
18              60                   70                    80   
19              75                   80                    65   

    Puzzle Solving skills  English Proficiency  Programming Skills  \
0                      75                   50                  90   
1                      80                   40                  80   
2                      85                   55                  88   
3                      80                   30                  80   
4                      90                   80                  85   
5                      84                   87                  83   
6                      60                   70                  70   
7                      75                   80                  65   
8                      60                   74                  70   
9                      85                   84                  90   
10                     79                   83                  72   
11                     93                   91                  94   
12                     83                   71 

In [31]:
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values
print(X)
print(Y)

[[85 85 90 ... 80 85  0]
 [89 90 85 ... 75 80  0]
 [80 85 90 ... 80 80  0]
 ...
 [66 52 68 ... 47 64  2]
 [62 65 62 ... 49 61  0]
 [64 64 61 ... 51 52  1]]
[52 44 60 30 95 85 75 80 72 87 73 96 55 93 45 60 65 55 70 65 85 45 52 63
 67 63 69 53 50 49 66 51 52 90 74 57 59 74 74 85 51 66 20 15 14 10 12 24
 26 30 31 32 25 27 26 28 25 20 19 15 14 10 66 72 73 71 74 59 55 64 62 64
 32 31 24 31 32 23 26 26 25 20 22 22 18 17 16 17 14 12 18 19 11 14 17 18
 14 10 29 47 39 35 36 38 37 36 34 35 30 26 25 89 85 84 86 87 89 88 85 75
 64 66 74]


In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)
X_train.shape, X_test.shape

((86, 15), (37, 15))

In [46]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import pickle as pk

# Read the dataset
dataset = pd.read_csv('D:\GITHUB\placementPredecitor\Book2 .csv')

# Preprocess the 'Placed' column as needed
# Example: Convert 'Placed' to binary values
dataset['Placed'] = np.where(dataset['Placed'] > 49, 1, 0)

# Extract feature matrix (X) and target vector (Y)
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

# Create and train models for Logistic Regression, Random Forest, SVM, KNN, Naive Bayes, and Decision Trees
models = {
    "Logistic Regression": LogisticRegression(),
    "Random Forest": RandomForestClassifier(random_state=42, n_jobs=-1, max_depth=5, n_estimators=100, oob_score=True),
    "SVM": SVC(kernel='rbf', C=1.0, gamma='scale'),  # Adjust hyperparameters here
    "K-Nearest Neighbors": KNeighborsClassifier(n_neighbors=5, p=2, weights='uniform'),  # Adjust hyperparameters here
    "Naive Bayes": GaussianNB(),
    "Decision Trees": DecisionTreeClassifier(max_depth=5, min_samples_leaf=1, criterion='gini')  # Adjust hyperparameters here
}

accuracies = {}

for model_name, model in models.items():
    model.fit(X_train, Y_train)
    predictions = model.predict(X_test)
    accuracy = accuracy_score(Y_test, predictions)
    accuracies[model_name] = accuracy
    print(f"Accuracy of {model_name}: {accuracy}")

# Save the best-performing model to a file (you can adjust based on accuracy)
best_model_name = max(accuracies, key=accuracies.get)
best_model = models[best_model_name]
file = pk.dump(best_model, open(f'{best_model_name}.pkl', 'wb'))

# Load the saved model and make predictions
loaded_model = pk.load(open(f'{best_model_name}.pkl', 'rb'))
prediction = loaded_model.predict([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])
print(f"Prediction using the loaded {best_model_name} model:", prediction)

regressor = RandomForestRegressor(random_state=42, n_jobs=-1, max_depth=5, n_estimators=100, oob_score=True)
regressor.fit(X_train, Y_train) 

d:\GITHUB\placementPredecitor\myEnv\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy of Logistic Regression: 0.9459459459459459
Accuracy of Random Forest: 0.972972972972973
Accuracy of SVM: 1.0
Accuracy of K-Nearest Neighbors: 1.0
Accuracy of Naive Bayes: 1.0
Accuracy of Decision Trees: 0.918918918918919
Prediction using the loaded SVM model: [1]


RandomForestRegressor(max_depth=5, n_jobs=-1, oob_score=True, random_state=42)

In [ ]:
dataset.head()
place_predict = regressor.fit(X_train, Y_train)

In [ ]:
place_predict.predict([[100,100,100,100,100,100,100,100,100,100,100,100,100,100,100]])

array([0.97])

In [ ]:
import pickle as pk
file = pk.dump(place_predict, open('place_predict.pkl', 'wb'))

In [ ]:
model = pk.load(open('place_predict.pkl', 'rb'))
model.predict([[100,100,100,100,100,100,100,100,100,100,100,100,100,100,100]])

array([0.97])